### ISSUE TITLE
Modify the options under the section "Final Diagnosis and Plan" to be the exact duplicate of the options under the updated section "Pathology Description" with just the addition of "Provider Name" and "Phone #"

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/smartcerv#102] opened 2019-06-10 18:51 UTC
* Normal
* Benign
* CIN 1/HPV
* CIN 2
* CIN 3
* Adenocarcinoma-in-situ
* Malignant
  * Microinvasive cancer
  * Squamous
  * Adenocarcinoma
  * Adenosquamous
* Insufficient for processing

**Comment by Mellorison** [comment] 2019-07-10 15:46
Modified the options under the section "Final Diagnosis and Plan" to be the exact duplicate of the options under the updated section "Pathology Description" with just the addition of "Provider Name" and "Phone #"

**Closed by Mellorison** 2019-07-10 15:46 UTC
Labels: LEEP, enhancement, v1.0.0-alpha.2
